### ISSUE TITLE
Variables in call

### ISSUE THREAD

**Issue by kae24** [davestewart/vuex-pathify#23]
Is it possible to use variables in the call helper?

**Comment by davestewart** [comment]
Can you provide an example of the functionality you are trying to achieve?

**Comment by kae24** [comment]
an instance of this would be, if an id for an object is passed in from vue-router
let say /ViewNode/someuuid

and i need to get a specific action from a registered module

`
call('node/' + node.id + '/actionname')
`

**Comment by davestewart** [comment]
I'm not sure if I understand you correctly, but I'll try to answer your question.

I think, you want the handler function created by the `call()` helper to be aware of the router at compile time?

This isn't possible, because at the time of creating the component, `this` points to towards the `window` object:

```js
import { call } from 'vuex-pathify'

export default {
  methods: {
    load: call('node/' + node.id + '/load') // node would point at window.node
  }
}
```

A [similar question](https://github.com/davestewart/vuex-pathify/issues/20) was asked the other day.

I think what you want is this (no pathify needed) ?

```js
export default {
  methods: {
    load () {
      this.$store.dispatch('node/' + this.$router.params.node.id + '/load')
    }
  }
}
```
