### ISSUE TITLE
It's literally total nonsense that we can't copy code from README

### ISSUE THREAD

**Issue by OzanKurt** [davestewart/vuex-pathify#32]

**Comment by davestewart** [comment]
Not really.

Vuex is a complex beast, and the abstractions which Pathify overlays to make things relatively simple require a small investment of time and learning at the start, which unfortunately the readme can't cover.

As such, there are fairly detailed docs which take you through setup and features, in a step by step manner. If you want to start using Pathify without taking a bit of time (say, 10 - 15 minutes) to go through them then you might feel a little thwarted.

You're obviously quite frustrated, so perhaps if you explain what you think the actual problem is (don't know where to start, have an error, etc) I can try and help you.

**Comment by davestewart** [comment]
Additionally, the readme's main job was to communicate the purpose of the plugin, where it may not be clear.

Granted, more people know about Pathify now, so it may be that I can reduce its length or rearrange the structure so that people get get to the good stuff sooner.

If you have any suggestions on what you think would be a good way to do this, I would be happy to consider them.

**Comment by josteph** [comment]
The article in [alligator ](https://alligator.io/vuejs/vuex-pathify/)has pretty much clear explanation about how this package works.

**Comment by OzanKurt** [comment]
I don't think that it's your decision to make if the package need some time to go over docs, there are people who is already pretty familiar with Vuex. It's all about the first impression. If i can't copy a piece of code from the repo and test it by myself, I personally, would not spend time learning it.

Good luck, 
also it is actually not that nice for you to ignore such a comment, and force people to read docs.
