### ISSUE TITLE
Why `@` for sub-properties ?

### ISSUE THREAD

**Issue by zaiste** [davestewart/vuex-pathify#33]
This is probably something obvious, but why do you need `@` for sub-properties instead of using just `.` (a dot) ? i.e.

This:

```js
get('widgets/filters.sort.key')
```

versus this:

```js
get('widgets/filters@sort.key')
```

**Comment by davestewart** [comment]
Hey zaiste,

It's a great question!

It could be one or two possible answers, but I would need to check the code to confirm.

Firstly, when I first dreamed up Pathify (or SuperStore as it was called when I was prototyping) I tried to imagine the general response from the Vuex community. Flux / Vuex being a bit hardcore generally attracts some hardcore users, and I wanted to be careful not to alienate them / risk having them criticise the approach for being too magic, or too tricksy.

Sub-property access was the "tricksy" bit. It allows developers to skip the supposedly architecturally-safe and verbose setup of mutations by mapping every store property to a corresponding mutation. Whilst I knew it was going to be really useful (I had a project where I was using this feature a LOT) I didn't want to risk it being written off by purists, so rather than just having dot notations, I decided to make the "opt-in" of sub-property access explicit by using the fairly common attribute-style identifier "@". I thought that by making each part of the path instantly recognisable, it would more intuitively communicate the intent of the path in question.

In hindsight, I could have done it either way, and to be honest I don't think it would be too much of a stretch to change the functionality.

However, this brings me onto my second point, which I think was that at some point I may have realised that I needed to make this explicit for the purposes of parsing the path into the JS code that actually gets / sets the values. I can't remember exactly the details now, it may be that I look again at it and could make it work either way.

But that's the rub!

I hope that helps.
