### ISSUE TITLE
support function getters

### ISSUE THREAD

**Issue by disarticulate** [davestewart/vuex-pathify#9]
When trying to run function getters with the get() function:
```
Error in created hook: "TypeError: Cannot read property '$store' of undefined"
```
//getters
```
export const zoomFromGeohash = (state) => {
  return item => {
    return state.precision[item].zoomFrom
  }
}
```
//component
```
  computed: {
    zoomFromGeohash: (w) => get('map/zoomFromGeohash')(w),
 }
```

**Comment by davestewart** [comment]
Hey Eric,

Thanks for spotting this - mapping function getters was not something I've ever considered doing.

I've updated `get()` to behave as you suggest, it makes sense.

You would use it as follows (by the way, your wrapped function is unnecessary!):

```js
computed: {
  zoomFromGeohash: get('map/zoomFromGeohash'),
}
```
```js
computed: {
  ...get(['map/zoomFromGeohash']),
}
```
```js
computed: {
  ...get('map', [
    'zoomFromGeohash'
  ]),
}
```

```js
$vm0.zoomFromGeohash(w)
```
However – and thanks – you prompted me to look at the code and it turns out I'd forgotten to document some functionality around this! For getter functions accessed using the global store accessors, you can pass the arguments within the call:

```js
const zoom = store.get('map/zoomFromGeohash', w)
```

This could be composed as an method, but currently the work done by the Pathify to resolve the store accessor it is not cached (it is on the to do list):

```js
methods: {
  getZoomFromGeohash (w) {
    return this.$store.get('map/zoomFromGeohash', w),
  }
}
```

Anyway, will push a fix shortly.

**Comment by disarticulate** [comment]
i'll check it out shortly. Thanks.

**Comment by tcaraccia** [comment]
Hey, i didn't quite get the resolution for this.
If I need to find an element in an array would do that by using selectors in a getter usualy like
```
 getById: state => id => state.items.find(item => item.id === id),
```
Is ther a way to do this straight foward from components with pathify ?

**Comment by davestewart** [comment]
Hello. Not totally sure what you mean.

Assuming you want to access getter on your store, you should be able to do this:

```js
this.$store.get('foo/getById', id)
```

Does that answer your question?
